IPD.InternalWeb/Controllers/AccountingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Web.Helpers;
using System.Web.UI.DataVisualization.Charting;

using Microsoft.Reporting.WebForms;
using IPD.Reports.DataGenerators;
using IPD.Service;
using IPD.Data.Accounting;

namespace IPD.InternalWeb.Controllers
{
    public class AccountingController : Controller
    {
        const string createtimePlaceholderText = "--creation time--";
        // GET: Accounting
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CollectionBatches()
        {
            var model = new Models.AccountingBatchesViewModel(AccountingBatch.AccountingBatchTypes.Collection);
            model.NewBatchActionName = "NewCollectionBatch";
            model.GetStatementsActionName = "GetCollectionStatements";
            model.NewBatch = new AccountingBatch() { Description = String.Format("Batch on: {0}", createtimePlaceholderText) };

            var accountingService = new AccountingService();
            using (var accountingContext = new IPDAccounting())
            {
                model.Batches = accountingService.GetAccountingBatches(accountingContext,
                    new AccountingBatch.AccountingBatchTypes[] { AccountingBatch.AccountingBatchTypes.Collection },
                    new AccountingBatch.AccountingBatchStatuses[] { 
                        AccountingBatch.AccountingBatchStatuses.New, 
                        AccountingBatch.AccountingBatchStatuses.Processing, 
                        //AccountingBatch.AccountingBatchStatuses.Canceled, 
                        AccountingBatch.AccountingBatchStatuses.Final,  }
                    ).ToList();
            }
            return View("~/Views/Accounting/AccountingBatches.cshtml", model);
        }


        [HttpGet]
        public ActionResult PaymentBatches()
        {
            var model = new Models.AccountingBatchesViewModel(AccountingBatch.AccountingBatchTypes.Payment);
            model.NewBatchActionName = "NewPaymentBatch";
            model.GetStatementsActionName = "GetPaymentStatements";
            model.NewBatch = new AccountingBatch() { Description = String.Format("Batch on: {0}",createtimePlaceholderText) };

            var accountingService = new AccountingService();
            using (var accountingContext = new IPDAccounting())
            {
                model.Batches = accountingService.GetAccountingBatches(accountingContext, 
                    new  AccountingBatch.AccountingBatchTypes[] {AccountingBatch.AccountingBatchTypes.Payment},
                    new AccountingBatch.AccountingBatchStatuses[] { 
                        AccountingBatch.AccountingBatchStatuses.New, 
                        AccountingBatch.AccountingBatchStatuses.Processing, 
                        //AccountingBatch.AccountingBatchStatuses.Canceled, 
                        AccountingBatch.AccountingBatchStatuses.Final,  }
                    ).ToList();
            }
            return View("~/Views/Accounting/AccountingBatches.cshtml", model);
        }

        [HttpPost]
        public ActionResult PaymentBatches(Models.AccountingBatchesViewModel model, string command)
        {
            switch(command)
            {
                case "Add": return NewPaymentBatch(model); break;
                case "SelectBatch": return SelectBatch(model); break;
                default: return PaymentBatches(); break;
            }
        }

        public ActionResult SelectBatch(Models.AccountingBatchesViewModel model)
        {
            //var model = pModel ?? new Models.AccountingBatchesViewModel(AccountingBatch.AccountingBatchTypes.Payment);
            var accountingService = new AccountingService();
            using (var accountingContext = new IPDAccounting())
            {
                model.Batches = accountingService.GetAccountingBatches(accountingContext, new AccountingBatch.AccountingBatchTypes[] { AccountingBatch.AccountingBatchTypes.Payment }).ToList();
                model.SelectedBatch = model.Batches.Where(b => b.id.ToString() == model.SelectedBatchId).FirstOrDefault();
            }
            return View("~/Views/Accounting/AccountingBatches.cshtml", model);

        }

        public JsonResult GetBatch(string pBatchId)
        {
            var accountingService = new AccountingService();
            using (var accountingContext = new IPDAccounting())
            {
                var batchId = new Guid(pBatchId);
                var rtn = (from ab in accountingContext.AccountingBatches
                            where ab.id == batchId
                            select new
                            {
                                batch = ab,
                                OrderCount = ab.OrderAccountingBatches.Count,
                                NextStep = "NextStep"                                
                            })
                            .FirstOrDefault();


                var nextStatus = AccountingBatch.GetNextStatus(rtn.batch.StatusString).ToString();
                var preventCancelStatus = from s in new AccountingBatch.AccountingBatchStatuses[] { AccountingBatch.AccountingBatchStatuses.Final, AccountingBatch.AccountingBatchStatuses.Canceled }
                                          select s.ToString();
                return Json(new
                {
                    rtn.batch.id,
                    Status = rtn.batch.StatusString,
                    rtn.batch.Description,
                    rtn.batch.UpdatedBy,
                    rtn.batch.CreatedDateTime,
                    rtn.batch.MessageHeader,
                    rtn.batch.Message,
                    rtn.OrderCount,
                    result = "success",
                    NextStep = nextStatus == rtn.batch.StatusString ? null : nextStatus,
                    AllowCancel = !preventCancelStatus.Contains(rtn.batch.StatusString)
                });
            }
        }

        public ActionResult NewPaymentBatch(Models.AccountingBatchesViewModel model)
        {
            if (model.BatchType != AccountingBatch.AccountingBatchTypes.Payment)
                throw new Exception("Invalid accounting type");

            NewAccountingBatch(model);

            return PaymentBatches();
        }

        public ActionResult NewCollectionBatch(Models.AccountingBatchesViewModel model)
        {
            if (model.BatchType != AccountingBatch.AccountingBatchTypes.Collection)
                throw new Exception("Invalid accounting type");

            NewAccountingBatch(model);
            return CollectionBatches();
        }
        private AccountingBatch NewAccountingBatch(Models.AccountingBatchesViewModel model)
        {

            var accountingService = new AccountingService();
            AccountingBatch batch = null;
            using (var accountingContext = new IPDAccounting())
            {
                try
                {
                    string description = null;
                    if (model.NewBatch != null)
                    {
                        description = model.NewBatch.Description;
                        if (description != null)
                            description = description.Replace(createtimePlaceholderText, String.Format("{0:dd-MMM-yyyy h:mm tt}", DateTime.Now));
                    }

                    switch(model.BatchType)
                    {
                        case AccountingBatch.AccountingBatchTypes.Collection:
                            batch = accountingService.CreateCollectionBatch(accountingContext, "unknownUser", model.AsOfDate, description);
                            break;
                        case AccountingBatch.AccountingBatchTypes.Payment:
                            batch = accountingService.CreatePaymentBatch(accountingContext, "unknownUser", model.BatchType, model.AsOfDate, description);
                            break;
                    }
                    
                    accountingContext.AccountingBatches.Add(batch);                    
                    accountingContext.SaveChanges();
                    
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException validationException)
                {
                    var msg = validationException.Message;
                    foreach(var error in validationException.EntityValidationErrors)
                    {
                        msg += String.Format("\r\n\r\ntype {0}:", error.Entry.Entity == null ? "null" : error.Entry.Entity.GetType().ToString());
                        foreach(var entry in error.ValidationErrors)
                        {
                            msg += String.Format("\r\n\t{0}: {1}", entry.PropertyName, entry.ErrorMessage);
                        }
                    }

                    System.Diagnostics.Debug.WriteLine(msg);
                    throw;
                }
                catch(Exception e)
                {
                    var innerExc = e;
                    string msg = string.Empty;
                    while (innerExc != null)
                    {
                        msg += String.Format("\r\n{0}", innerExc.Message);
                        innerExc = innerExc.InnerException;
                    }
                    System.Diagnostics.Debug.WriteLine(msg);
                    throw;
                }
            }

            return batch;
        }

        public JsonResult AdvanceBatchStatus(AccountingBatch model)
        {
            var accountingService = new AccountingService();
            AccountingBatch.AccountingBatchStatuses newBatchStatus = AccountingBatch.AccountingBatchStatuses.New;
            if (model != null)
            {
                using (var accountingContext = new IPDAccounting())
                {

IPD.InternalWeb/Views/Shared/_DriverSearch.cshtml
<fieldset class="card">
    <label>Driver Search <span class="fyiNote">(Mobile # or search by name)</span> </label>
    <input autocomplete="off" id="MobileNumber" name="MobileNumber" type="text" value="@ViewBag.MobileNumber" class="ui-autocomplete-input">
    
        <label>Driver:</label>
        <label>@ViewBag.DriverName</label>
        <label>Status <span class="fyiNote">(Oracle.Driver.DRV_STATUS)</span>:</label>
        <label>@ViewBag.DriverStatus</label>

    <input type="submit" value="Go" />
</fieldset>

IPD.InternalWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Scripts.Render("~/bundles/modernizr")

    @RenderSection("AdditionalHead", false)

    @Styles.Render("~/Content/css")


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        
        <div class="container">
            <img src="~/img/IPD_Shield_SPOT 64x64.png" class="header-logo" />
            <div class="navbar-header">
                
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>                
                
                @*@Html.ActionLink("IPD Driver", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@                
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Collection Processing", "CollectionBatches", "Accounting")</li>
                    <li>@Html.ActionLink("Payment Processing", "PaymentBatches", "Accounting")</li>
                    <li>@*@Html.ActionLink("Driver Statements", "PaymentProcessing", "Home")*@</li>
                    <li>@Html.ActionLink("Recent Drivers", "DriverList", "Home")</li>
                    <li>@Html.ActionLink("Driver Activity", "DriverActivity", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        @*<footer>
            <p>&copy; @DateTime.Now.Year - IPD Mobile / Datatrac, Inc.</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>